version: "3"

services:
  dev-enviroment:
    build: .
    image: serverless-aws-node-dynamodb:dev-enviroment
    container_name: dev-enviroment
    user: root
    ports:
      - 8081:8081
    volumes:
      - .:/app/.
    env_file:
      ./.env