version: "3"

services:
  dev-enviroment:
    build: .
    image: serverless-aws-node:dev-enviroment
    container_name: dev-enviroment
    user: root
    ports:
      - 8080:8080
    volumes:
      - .:/app/.